//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResourcesManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HumanResourcesManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add project.
        /// </summary>
        public static string addProject {
            get {
                return ResourceManager.GetString("addProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalan.
        /// </summary>
        public static string ca_ES {
            get {
                return ResourceManager.GetString("ca-ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        public static string dates {
            get {
                return ResourceManager.GetString("dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database has been initialized successfully..
        /// </summary>
        public static string dbInitialized {
            get {
                return ResourceManager.GetString("dbInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deductions.
        /// </summary>
        public static string deductions {
            get {
                return ResourceManager.GetString("deductions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string departmentsTitle {
            get {
                return ResourceManager.GetString("departmentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition Mode.
        /// </summary>
        public static string editionMode {
            get {
                return ResourceManager.GetString("editionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact information.
        /// </summary>
        public static string employeeContactInfo {
            get {
                return ResourceManager.GetString("employeeContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string employeeDepartment {
            get {
                return ResourceManager.GetString("employeeDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string employeeEmail {
            get {
                return ResourceManager.GetString("employeeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesional Information.
        /// </summary>
        public static string employeeEmploymentInfo {
            get {
                return ResourceManager.GetString("employeeEmploymentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string employeeFirstName {
            get {
                return ResourceManager.GetString("employeeFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire Date.
        /// </summary>
        public static string employeeHireDate {
            get {
                return ResourceManager.GetString("employeeHireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string employeeLastName {
            get {
                return ResourceManager.GetString("employeeLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee name.
        /// </summary>
        public static string employeeName {
            get {
                return ResourceManager.GetString("employeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees per Department.
        /// </summary>
        public static string employeePerDepartment {
            get {
                return ResourceManager.GetString("employeePerDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees per Project.
        /// </summary>
        public static string employeePerProject {
            get {
                return ResourceManager.GetString("employeePerProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string employeePhoneNumber {
            get {
                return ResourceManager.GetString("employeePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string employeePosition {
            get {
                return ResourceManager.GetString("employeePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string employeeSalary {
            get {
                return ResourceManager.GetString("employeeSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string employeesTitle {
            get {
                return ResourceManager.GetString("employeesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string en_EN {
            get {
                return ResourceManager.GetString("en-EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string es_ES {
            get {
                return ResourceManager.GetString("es-ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General information.
        /// </summary>
        public static string generalInfo {
            get {
                return ResourceManager.GetString("generalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Database.
        /// </summary>
        public static string generateDatabase {
            get {
                return ResourceManager.GetString("generateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate payroll.
        /// </summary>
        public static string generatePayroll {
            get {
                return ResourceManager.GetString("generatePayroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross salary.
        /// </summary>
        public static string grossSalary {
            get {
                return ResourceManager.GetString("grossSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net salary.
        /// </summary>
        public static string netSalary {
            get {
                return ResourceManager.GetString("netSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay day.
        /// </summary>
        public static string payDay {
            get {
                return ResourceManager.GetString("payDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        public static string projectBudget {
            get {
                return ResourceManager.GetString("projectBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string projectDescription {
            get {
                return ResourceManager.GetString("projectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Date.
        /// </summary>
        public static string projectEndDate {
            get {
                return ResourceManager.GetString("projectEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the Project.
        /// </summary>
        public static string projectName {
            get {
                return ResourceManager.GetString("projectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string projectStartDate {
            get {
                return ResourceManager.GetString("projectStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string projectStatus {
            get {
                return ResourceManager.GetString("projectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string projectsTitle {
            get {
                return ResourceManager.GetString("projectsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerate Database..
        /// </summary>
        public static string regenerateDatabase {
            get {
                return ResourceManager.GetString("regenerateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to the list.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string saveChanges {
            get {
                return ResourceManager.GetString("saveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to regenerate the database? Select an SQL file, this project contains build.sql. This may take a few minutes..
        /// </summary>
        public static string txtWantToRegenerateDB {
            get {
                return ResourceManager.GetString("txtWantToRegenerateDB", resourceCulture);
            }
        }
    }
}
